library(readxl)
pokemon=read_excel(path="pokemon.xlsx",sheet="pokemon")
dim(pokemon)
nrow(pokemon)
ncol(pokemon)
summary(pokemon)
pokemon$is_legendary=as.factor(pokemon$is_legendary)
pokemon$generation=as.factor(pokemon$generation)
pokemon$type=as.factor(pokemon$type)
summary(pokemon)
med=median(pokemon$attack)
pokemon$attack_group=ifelse(pokemon$attack>=med,"attack+","attack-")
pokemon$attack_group=as.factor(pokemon$attack_group)
summary(pokemon$attack_group)

pokemon$water_fire=ifelse(pokemon$type=="water" | pokemon$type=="fire","yes","no")
pokemon$water_fire=as.factor(pokemon$water_fire)
summary(pokemon$water_fire)

qa3=quantile(pokemon$attack,probs=0.75)
qd3=quantile(pokemon$defense,probs=0.75)         
qs3=quantile(pokemon$speed,probs=0.75)
pokemon$best=ifelse(pokemon$attack>=qa3 & pokemon$defense>=qd3 & pokemon$speed>=qs3,"yes","no")
pokemon$best=as.factor(pokemon$best)
summary(pokemon$best)
requete=subset(pokemon,is.na(weight_kg))
View(requete)
nrow(requete)
requete2=subset(pokemon,!is.na(weight_kg))
View(requete2)
nrow(requete2)


pokemon$weight_kg=as.factor(pokemon$weight_kg)
pokemon$weight_kgNa=ifelse(is.na(pokemon$weight_kg),median(pokemon$weight_kg,na.rm=TRUE),pokemon$weight_kg)

pokemon$weight_kg=as.factor(pokemon$weight_kg)
pokemon$weight_height_mNa=ifelse(is.na(pokemon$height_m),median(pokemon$height_m,na.rm=TRUE),pokemon$height_m)
pokemon$height_mNa=as.factor(pokemon$height_m)
summary(pokemon$weight_kgNa)
summary(pokemon$weight_height_mNa)
